### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sujaldev** [sujaldev/fedora-post-install#1]
## High Priority
- [ ] Install [vistube](https://github.com/sujaldev/vistube)
- [ ] Add some more shortcuts
  - cycle windows: alt + tab
  - show desktop: super + d
  - switch workspace: alt + 1, 2, 3, 4
- [ ] Remove hard-coded parameters
- [ ] Auto detect GPU, WiFi and change parameters accordingly
- [ ] The .profile model is not working, change to a manual post reboot script

## Low Priority
- [ ] Better output
- [ ] Remove the wallpaper status, doesn't look as cool as I initially thought
- [ ] Support Fedora 36 (auto detect)
- [ ] Automate GitHub ssh key upload
- [ ] Automate chrome profile initialization

**Comment by sujaldev** [comment]
Closing this as I no longer use f35 and have switched to f36 and so this repository is useless to me now.
